[build]
  publish = "."

[[redirects]]
  from = "https://www.zvuk-v-hramah.com/*"
  to = "https://zvuk-v-hramah.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://zvuk-v-hramah.ru/*"
  to = "https://zvuk-v-hramah.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.zvuk-v-hramah.ru/*"
  to = "https://zvuk-v-hramah.com/:splat"
  status = 301
  force = true
